### ISSUE TITLE
No handler found for the command: 'fake.fakeBuild'

### ISSUE THREAD

**Issue by nicolocodev** [ionide/ionide-vscode-fake#4]
Using the `FAKE: Build` command i get the message: `No handler found for the command: 'fake.fakeBuild'` But works well on ionide-fake-Atom.
![warn](https://cloud.githubusercontent.com/assets/4001191/11485501/7e7e2196-9781-11e5-8a21-f1325e38cd71.png)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.0.2`

**Comment by forki** [comment]
I had the same issue. What was the problem?

**Comment by Krzysztof-Cieslak** [comment]
I'm not sure actually... it just magically gone away after I've built new version. Maybe there were some problem with release previously.

**Comment by jwood803** [comment]
I'll update this and see how it goes. Thanks @Krzysztof-Cieslak!

**Comment by jwood803** [comment]
Does this look correct for the versions? Seems I'm on `1.0.3` yet I still get the issue.

![image](https://cloud.githubusercontent.com/assets/1578160/11512846/3554f57c-983e-11e5-804b-28fff06c6143.png)

**Comment by Krzysztof-Cieslak** [comment]
Can you try again? `1.0.4`

**Comment by JonCanning** [comment]
Same for me

**Comment by jwood803** [comment]
Unfortunately, the package for this is still on `1.0.3` and I don't see any updates.

**Comment by bcachet** [comment]
I have the same problem with v1.0.8
Maybe it's related to the fact that it's a C# project and not a F# one.
You can find project here: https://github.com/bcachet/QuantityNet

**Comment by jlewicki** [comment]
I have the same problem :( v 1.0.8

**Comment by drb2k2** [comment]
running npm install toml in the folder %userprofile%\.vscode\extensions\Ionide.Ionide-FAKE
fixed this for me. Not a fix but a patch if you need this module to run.

**Comment by featuresnap** [comment]
@drb2k2 thanks for your suggestion. This workaround got me up and running

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.0.10`.
